update pre-commit

diff --git a/scripts/hooks/pre-commit b/scripts/hooks/pre-commit
--- a/scripts/hooks/pre-commit
+++ b/scripts/hooks/pre-commit
@@ -16,18 +16,18 @@ hooks_utility_ensure_changelog_edited 'CHANGELOG.md'
 
 # make sure version is bumped when finish feature branch
 pattern='^# version: *v[0-9.]+'
-hooks_utility_ensure_version_updated 'hooks-utility.sh' "${pattern}"
+hooks_utility_ensure_version_updated 'hooks_utility.sh' "${pattern}"
+
+# make sure hooks_utility.sh contains no AM
+if [[ $(get_commit_type_at_pre_commit) == "merge-binary-release" ]]; then
+    PATTERN="${PRIMARY_AM_PATTERN}|${SECONDARY_AM_PATTERN}|${TERTIARY_AM_PATTERN}"
+    if git diff --cached --unified=0 --no-color hooks_utility.sh |
+        grep -E -q -- "$PATTERN"; then
+        echo "hooks_utility.sh must contains no AM at all" | hooks_utility_fail
+        exit 1
+    fi
+fi
 
 echo "pre-commit" | hooks_utility_pass
 
 exit 0
-
-# make sure hooks_utility.sh contains no AM
-# Todo need test
-if [[ $(get_commit_type_at_pre_commit) == "merge-binary-release" ]]; then
-    PATTERN=
-    "${PRIMARY_AM_PATTERN}|${SECONDARY_AM_PATTERN}|${TERTIARY_AM_PATTERN}"
-    if git diff --cached --no-color | grep -E -q -- "$PATTERN"; then
-        exit 1
-    fi
-fi
